public.plot.gca.linewidth = 3;
public.plot.gca.fontname = 'Times New Roman';
public.plot.gca.fontsize = 16;
public.plot.gca.ws_x = 0.48*2;
public.plot.gca.ws_y = 0.3354*2;
public.plot.gca.width = 4.5208;
public.plot.gca.height = 3.5656;
% postprocessing, to visualize the points in space
exist = Monte_3D(:,'num of LCO');
exist = table2array(exist);
data_abs = Monte_3D(exist>0,:);
%
type_LCO = table2array(data_abs(:,'sign V'));

% according to the type of SPE or SAE, divide the data set to two 
SPE = data_abs(type_LCO>0,:);
SAE = data_abs(type_LCO<0,:);

% into 2 subsets by the stability
SPE_max = table2array(SPE(:,'Max'));
SAE_max = table2array(SAE(:,'Max'));

SPE_us = SPE(SPE_max>1,:);
SPE_s = SPE(SPE_max<=1,:);

SAE_us = SAE(SAE_max>1,:);
SAE_s = SAE(SAE_max<=1,:);

FIG1=figure;
%
h1=scatter3(table2array(SAE_s(:,'lambda_1')),...
    table2array(SAE_s(:,'lambda_2')),...
    table2array(SAE_s(:,'b3')),...
    16,...
    'MarkerFaceColor',[1 0 0]);

hold on

h2=scatter3(table2array(SAE_us(:,'lambda_1')),...
    table2array(SAE_us(:,'lambda_2')),...
    table2array(SAE_us(:,'b3')),...
    2,...
    'MarkerFaceColor',[1 .75  0]);
%
h3=scatter3(table2array(SPE_s(:,'lambda_1')),...
    table2array(SPE_s(:,'lambda_2')),...
    table2array(SPE_s(:,'b3')),16,...
    'MarkerFaceColor',[0 0 1 ]);
hold on
h4=scatter3(table2array(SPE_us(:,'lambda_1')),...
    table2array(SPE_us(:,'lambda_2')),...
    table2array(SPE_us(:,'b3')),6,...
    'MarkerFaceColor',[0. 0.75 1]);
xlabel('\lambda_1')
ylabel('\lambda_2')
zlabel('b_3')
legend([h1 h2 h3 h4],{'$SAE_s$','$SAE_{us}$','$SPE_s$','$SPE_{us}$'},'interpreter','latex','location','best')
set(gca,'fontsize',public.plot.gca.fontsize,...
        'fontname',public.plot.gca.fontname,...
        'linewidth',public.plot.gca.linewidth,...
        'Units','inches',...
        'position',[public.plot.gca.ws_x  public.plot.gca.ws_y ...
     public.plot.gca.width public.plot.gca.height])
 pos = get(FIG1,'Position');
    set(FIG1, 'PaperUnits', 'inches','PaperPosition', ...
    [0  0 ...
    public.plot.gca.width  public.plot.gca.height],...
    'PaperSize', pos(3:4));
