function [A,B,C,R,T_2_det,T_2_d_det_dt] = par2NForm_Lienard(par)
%> use the normal form parameters to form the matrixes
if isreal(par(1))
lambda_1 = par(1) + par(2)*sqrt(-1);
lambda_2 = par(1) - par(2)*sqrt(-1);
else
lambda_1 = par(1);
lambda_2 = par(2);

end
lambda_3 = par(3);
b2       = par(4);
b3       = par(5);

a1 = lambda_1 + lambda_2 + lambda_3;
a2 = -(lambda_1 * lambda_2 + lambda_2*lambda_3 + lambda_1*lambda_3);
a3 = lambda_1 * lambda_2 * lambda_3;

A = [a1 1 0;a2 0 1; a3 0 0];
B = [0; b2; b3];
C = [1,0,0];
R = eye(length(C)) - B*C*A;
%>
numer = @(t) -(lambda_2 - lambda_3)*(lambda_1 - lambda_2)*(lambda_1 - lambda_3)*...
    (-1 + b2)*exp(t*(lambda_1 + lambda_2 + lambda_3)) + ((lambda_2 - lambda_3)*...
    (-1 + b2)*lambda_1 - ((-1 + b2)*lambda_2 + b3 + lambda_3)*lambda_3)*...
    (lambda_1 - lambda_2)*exp(t*(lambda_1 + lambda_2)) + ((lambda_2 - lambda_3)*...
    (-1 + b2)*lambda_1 + lambda_2*(lambda_2 + (-1 + b2)*lambda_3 + b3))*...
    (lambda_1 - lambda_3)*exp(t*(lambda_1 + lambda_3)) - (lambda_1^2 + ((-1 + b2)...
    *lambda_2 + (-1 + b2)*lambda_3 + b3)*lambda_1 - lambda_2*lambda_3*(-1 + b2))...
    *(lambda_2 - lambda_3)*exp(t*(lambda_2 + lambda_3)) - (lambda_2 - lambda_3)*...
    ((-1 + b2)*lambda_1^2 + (b3 + lambda_2 + lambda_3)*lambda_1 - lambda_2*lambda_3)...
    *exp(t*lambda_1) + (lambda_1 - lambda_3)*(lambda_1*(lambda_2 - lambda_3) + ...
    ((-1 + b2)*lambda_2 + b3 + lambda_3)*lambda_2)*exp(t*lambda_2) - ...
    (((-lambda_2 + lambda_3)*lambda_1 + lambda_3*(lambda_2 + (-1 + b2)*lambda_3 + b3))*...
    exp(t*lambda_3) + (lambda_2 - lambda_3)*(lambda_1 - lambda_3))*(lambda_1 - lambda_2);
denom = (lambda_2 - lambda_3)*(lambda_1 - lambda_2)*(lambda_1 - lambda_3);

diff_det_t = @(t) -(lambda_2 - lambda_3)*(lambda_1 - lambda_2)*(lambda_1 - lambda_3)...
    *(-1 + b2)*(lambda_1 + lambda_2 + lambda_3)*exp(t*(lambda_1 + lambda_2 + lambda_3)) ...
    + ((lambda_2 - lambda_3)*(-1 + b2)*lambda_1 - lambda_3*((-1 + b2)*lambda_2 + b3 + lambda_3))*...
    (lambda_1 - lambda_2)*(lambda_1 + lambda_2)*exp(t*(lambda_1 + lambda_2)) + ...
    (lambda_1 - lambda_3)*((lambda_2 - lambda_3)*(-1 + b2)*lambda_1 + (lambda_2 +...
    (-1 + b2)*lambda_3 + b3)*lambda_2)*(lambda_1 + lambda_3)*exp(t*(lambda_1 + lambda_3)) ...
    - (lambda_1^2 + ((-1 + b2)*lambda_2 + (-1 + b2)*lambda_3 + b3)*lambda_1 - ...
    lambda_2*lambda_3*(-1 + b2))*(lambda_2 - lambda_3)*(lambda_2 + lambda_3)*exp(t*(lambda_2 + lambda_3)) ...
    - ((-1 + b2)*lambda_1^2 + (b3 + lambda_2 + lambda_3)*lambda_1 - lambda_2*lambda_3)*...
    (lambda_2 - lambda_3)*lambda_1*exp(t*lambda_1) + (lambda_1*(lambda_2 - lambda_3) ...
    + lambda_2*((-1 + b2)*lambda_2 + b3 + lambda_3))*(lambda_1 - lambda_3)*lambda_2*exp(t*lambda_2) ...
    - ((-lambda_2 + lambda_3)*lambda_1 + (lambda_2 + (-1 + b2)*lambda_3 + b3)*lambda_3)...
    *lambda_3*exp(t*lambda_3)*(lambda_1 - lambda_2);


T_2_det = @(t) real(numer(t)./denom);
T_2_d_det_dt = @(t) real(diff_det_t(t)./denom);
end