%> the 2D poincare map substracted from the 3D case

%  the denom is defined in the previous *.m file
T = roots(1);
% denom = (lambda_2 - larmbda_3)*(lambda_1 - lambda_2)*(lambda_1 - lambda_3);
%>
Pmp_a11_numer = @(t) - b2*(lambda_1 + lambda_2 + lambda_3)*(lambda_1*exp(t*lambda_1)*(lambda_2 - lambda_3) ...
    - lambda_2*(lambda_1 - lambda_3)*exp(t*lambda_2) + lambda_3*exp(t*lambda_3)*(lambda_1 - lambda_2))...
    + (1 - b2)*((-lambda_2^2 + lambda_3^2)*lambda_1*exp(t*lambda_1) + (lambda_1^2*lambda_2 - lambda_2*lambda_3^2)...
    *exp(t*lambda_2) - lambda_3*exp(t*lambda_3)*(lambda_1 - lambda_2)*(lambda_1 + lambda_2));
%>
Pmp_a11 = Pmp_a11_numer(T)./denom;
%>
Pmp_a12_numer  =@(t) -b2*(lambda_1 + lambda_2 + lambda_3)*((lambda_2 - lambda_3)*exp(t*lambda_1) + ...
    (-lambda_1 + lambda_3)*exp(t*lambda_2) + exp(t*lambda_3)*(lambda_1 - lambda_2))...
    + (1 - b2)*((-lambda_2^2 + lambda_3^2)*exp(t*lambda_1) + (lambda_1^2 - lambda_3^2)*exp(t*lambda_2) ...
    + (-lambda_1^2 + lambda_2^2)*exp(t*lambda_3));
%>
Pmp_a12 = Pmp_a12_numer(T)./denom;

%> 
Pmp_a21_numer = @(t) -b3*(lambda_1 + lambda_2 + lambda_3)*(lambda_1*exp(t*lambda_1)*(lambda_2 - lambda_3) -...
    lambda_2*(lambda_1 - lambda_3)*exp(t*lambda_2) + lambda_3*exp(t*lambda_3)*(lambda_1 - lambda_2))...
    - b3*((-lambda_2^2 + lambda_3^2)*lambda_1*exp(t*lambda_1) + (lambda_1^2*lambda_2 - lambda_2*lambda_3^2)...
    *exp(t*lambda_2) - lambda_3*exp(t*lambda_3)*(lambda_1 - lambda_2)*(lambda_1 + lambda_2))...
    -lambda_3*((-lambda_2 + lambda_3)*exp(t*lambda_1) + (lambda_1 - lambda_3)*exp(t*lambda_2) - exp(t*lambda_3)*...
    (lambda_1 - lambda_2))*lambda_2*lambda_1;

Pmp_a21 = Pmp_a21_numer(T)./denom;

%>
Pmp_a22_numer = @(t) -b3*(lambda_1 + lambda_2 + lambda_3)*((lambda_2 - lambda_3)*exp(t*lambda_1) + ...
    (-lambda_1 + lambda_3)*exp(t*lambda_2) + exp(t*lambda_3)*(lambda_1 - lambda_2)) ...
    -b3*((-lambda_2^2 + lambda_3^2)*exp(t*lambda_1) + (lambda_1^2 - lambda_3^2)*exp(t*lambda_2) + ...
    (-lambda_1^2 + lambda_2^2)*exp(t*lambda_3))+ lambda_2*lambda_3*(lambda_2 - lambda_3)*exp(t*lambda_1) + ...
    (-lambda_3*(lambda_1 - lambda_3)*exp(t*lambda_2) + exp(t*lambda_3)*lambda_2*(lambda_1 - lambda_2))*lambda_1;

Pmp_a22 = Pmp_a22_numer(T)./denom;

Pmp = real([Pmp_a11, Pmp_a12; Pmp_a21, Pmp_a22]);
eig(Pmp)

Mono_matrix     = R*expm(A*T)
[V,D]           = eig(Mono_matrix)
